You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

CODE:

class Solution {
    public char findTheDifference(String s, String t) {
        char res = 0;
        for(int i=0;i<s.length();i++){
            res ^= s.charAt(i);
        }
        for(int i=0;i<t.length();i++){
            res ^= t.charAt(i);
        }
        return res;
    }
}

OUTPUT:

Runtime
2
ms
Beats
66.42%

//ANOTHER APPROACH:

CODE:

class Solution {
    public char findTheDifference(String s, String t) {
        char[] sarr = s.toCharArray();
        char[] tarr = t.toCharArray();
        Arrays.sort(sarr);
        Arrays.sort(tarr);
        for(int i=0;i<sarr.length;i++){
            if(sarr[i]!=tarr[i]){
                return tarr[i];
            }
        }
        return tarr[tarr.length-1];
    }
}

OUTPUT:

Runtime
3
ms
Beats
38.92%
